version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - app_config:/app/config # Подключаем volume для конфигурационного файла
    depends_on:
      - db
    environment:
      - APP_ENV=production
    command: ["sh", "-c", "if [ ! -f /app/config/config.yaml ]; then ./main --generate-config && mv config.yaml /app/config/config.yaml; fi && ./main"]
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: yggdrasil_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yggdrasil_db
      MYSQL_USER: yggdrasil_user
      MYSQL_PASSWORD: yggdrasil_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  app_config:
  db_data:
